.\" Copyright (c) 2025 The FreeBSD Foundation
.\"
.\" SPDX-License-Identifier: BSD-2-Clause
.\"
.Dd July 9, 2026
.Dt AQ 4
.Os
.Sh NAME
.Nm aq
.Nd Aquantia / Marvell AQC1xx Ethernet driver
.Sh SYNOPSIS
To compile this driver into the kernel, place the following lines in your
kernel configuration file:
.Bd -ragged -offset indent
.Cd "device aq"
.Ed
.Pp
To load the driver as a module at boot time, place the following line in
.Xr loader.conf 5 :
.Bd -literal -offset indent
if_aq_load="YES"
.Ed
.Sh DESCRIPTION
The
.Nm
device driver provides support for PCIe 1/2.5/5/10 Gigabit Ethernet adapters
based on
Aquantia (now Marvell) AQtion AQC1xx Ethernet controllers.
.Pp
For more information on configuring this device, see
.Xr ifconfig 8 .
.Pp
The
.Nm
driver is experimental, and has a number of caveats and limitations.
.Sh HARDWARE
The
.Nm
driver supports the following PCIe Ethernet controllers:
.Pp
.Bl -bullet -compact
.It
aQuantia AQC100 (10 Gigabit)
.It
aQuantia AQC100S (10 Gigabit)
.It
aQuantia AQC107 (10 Gigabit)
.It
aQuantia AQC107S (10 Gigabit)
.It
aQuantia AQC108 (5 Gigabit)
.It
aQuantia AQC108S (5 Gigabit)
.It
aQuantia AQC109 (2.5 Gigabit)
.It
aQuantia AQC109S (2.5 Gigabit)
.It
aQuantia AQC111 (5 Gigabit)
.It
aQuantia AQC111S (5 Gigabit)
.It
aQuantia AQC112 (2.5 Gigabit)
.It
aQuantia AQC112S (2.5 Gigabit)
.It
Marvell AQC113 (10 Gigabit)
.It
Marvell AQC113C (10 Gigabit)
.It
Marvell AQC113CA (10 Gigabit)
.It
Marvell AQC113CS (10 Gigabit)
.It
Marvell AQC114CS (5 Gigabit)
.It
Marvell AQC115C (2.5 Gigabit)
.It
Marvell AQC116C (1 Gigabit)
.El
.Pp
The AQC100 and AQC100S are SFP+ controllers;
the remainder use twisted-pair media.
.Pp
Only the AQC113 through AQC116 support 10 Megabit operation;
the remaining controllers negotiate no slower than 100 Megabit.
.Sh SEE ALSO
.Xr arp 4 ,
.Xr miibus 4 ,
.Xr ifconfig 8
